services:
  main-service:
    build: main-service
    image: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
    environment:
      STATS_SERVER_URL: http://stats-server:9090
      SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5434/main
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: iamroot

  main-db:
    image: postgres:16.1
    container_name: postgres-main-db
    ports:
      - "6544:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-service:
        build: stats/stats-service
        image: stats-service
        container_name: stats-service-container
        ports:
          - "9090:9090"
        depends_on:
          stats-db:
            condition: service_healthy
        environment:
          MAIN_SERVER_URL: http://main-server:8080
          SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
          SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: iamroot

  stats-db:
        image: postgres:16.1
        container_name: postgres-stats-db
        ports:
          - "6543:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=iamroot
          - POSTGRES_DB=stats
        healthcheck:
          test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
          timeout: 5s
          interval: 5s
          retries: 10